### ISSUE TITLE
Javascript error when js is minified and merge

### ISSUE THREAD

**Issue by Kandax86** [macbookandrew/cf7-google-analytics#11]
hi,
when we have js minification and merge it seems this code 

```
wp_add_inline_script( 'wpcf7-ga-events', 'var cf7GASendActions = ' . wp_json_encode( $this->get_send_actions( 'all' ) ) . ', cf7FormIDs = ' . $this->get_form_ids(), 'before' );"
```
generate an error because of ";" that is missing at the end of the line

the only way i found to fix this is to add this ";" in the js generated as :

```
wp_add_inline_script( 'wpcf7-ga-events', 'var cf7GASendActions = ' . wp_json_encode( $this->get_send_actions( 'all' ) ) . ', cf7FormIDs = ' . $this->get_form_ids().';', 'before' );
```
just after $this->get_form_ids()

so

$this->get_form_ids().';'

no more issues now

https://github.com/macbookandrew/cf7-google-analytics/blob/ce69dc799a9bd9a2c260e2678bad37a208ed6585/inc/class-cf7-google-analytics.php#L197C3-L197C3

**Comment by macbookandrew** [comment]
@Kandax86 thanks; v1.8.10 includes a fix for this
