### ISSUE TITLE
Uses general As event category

### ISSUE THREAD

**Issue by oempire** [macbookandrew/cf7-google-analytics#2]
hi in the Docs it says it uses Contact Form as the event category, but im here testing now and can see in real time its showing the event category as general

**Comment by macbookandrew** [comment]
Do you have a public test site?

**Comment by oempire** [comment]
Hi, you can see at http://urlgone.com/d35b1a/ Contact Form

**Comment by macbookandrew** [comment]
Can you try [this update](https://github.com/macbookandrew/cf7-google-analytics/archive/v1.4.1.zip)? Looks like an issue with gtag.js event tracking.
