### ISSUE TITLE
Issue with 1.7.1 update

### ISSUE THREAD

**Issue by qrusnell** [macbookandrew/cf7-google-analytics#3]
Front end error after 1.7.1 update:

Notice: Use of undefined constant WPCF7_VERSION - assumed 'WPCF7_VERSION' in /home/fortelaw/public_html/wp-content/plugins/cf7-google-analytics/cf7-google-analytics.php on line 31

WP 4.9.4
CF7 5.0.1
PHP 5.6.34

**Comment by macbookandrew** [comment]
@qrusnell Thanks; [v1.7.2](https://github.com/macbookandrew/cf7-google-analytics/releases/tag/v1.7.2) should fix this issue.
