### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by MikeMcPeak** [macbookandrew/cf7-google-analytics#4]
I installed your Contact Form & Google Analytics plugin on Friday, and despite having several form submissions over the weekend, I have not seen any events firing in GA.

I am using Contact Form 7 Version 4.9.2 in Wordpress 4.9.5. I have my tracking code installed via GTM. Is there any additional configuration needed?

**Comment by macbookandrew** [comment]
Yes, you’ll need to set up a tag and trigger in Google Tag Manager.

Can you try these instructions and see if it starts working for you? https://github.com/macbookandrew/cf7-google-analytics#how-to-i-use-this-with-google-tag-manager-gtmjs

Thanks

**Comment by MikeMcPeak** [comment]
Thank you. Sorry I did not see that section earlier. I saw the top portion and thought it was the same information as on the wordpress plugin page, which lacks the gtm info.

**Comment by macbookandrew** [comment]
I just wrote it 😀

Please let me know if it makes sense and works and if so, I’ll add to the WordPress plugin readme as well.

Andrew Minion | Web Developer
andrew@andrewrminion.com | 704-769-0625

**Comment by MikeMcPeak** [comment]
I feel like that should work, but the tag is not firing in preview mode. Looking at the data layer, I am not seeing the event:

![image](https://user-images.githubusercontent.com/11053287/39013250-d0334b30-43e4-11e8-9784-3ac43f80c57a.png)

**Comment by macbookandrew** [comment]
Even after submitting a form it doesn’t show up in the data layer? Any idea if you’re using a custom-named data layer?

**Comment by MikeMcPeak** [comment]
I don't believe so. This is what I found. I asked me dev and he said he doesn't know why there would be a custom one.

![image](https://user-images.githubusercontent.com/11053287/39147522-db82519a-4707-11e8-9ec4-a09dd25e312b.png)

**Comment by MikeMcPeak** [comment]
OK, so I figured out the issue. For some reason it just was not working in preview and debug mode. I had to publish the container version to get another tag someone requested, and they suddenly started popping up. Sorry for the confusion.

**Comment by macbookandrew** [comment]
Thanks for the update; I’ll update the plugin with those instructions.
