### ISSUE TITLE
How to set the goal for one specific form

### ISSUE THREAD

**Issue by richicru** [macbookandrew/cf7-google-analytics#6]
Reading the instructions I see: "Optionally add a label if you want to define a goal for one specific form" but it doesn't say how to do it. Do we have to put the form ID in the "label", or the form slug?
¿Is there any way to specify the form URL where the event comes from?
Thanks

**Comment by macbookandrew** [comment]
@richicru Use the name of the form. I’ll update the instructions to reflect that; thanks.
