### ISSUE TITLE
no event logging

### ISSUE THREAD

**Issue by brbowers** [macbookandrew/cf7-google-analytics#7]
I have 1.8.0 installed and no events are logging in real-time GA. I've tried the old analytics.js code, the new asynch analytics.js and the gtag.js code. No luck on any of those.

Did not get mail sent or sent when I activated the plugin.
I am receiving the form submissions in my email.

Aside from moving to gtm is there any other troubleshooting I can do with either analytics.js or gtag.js?

**Comment by jsadd19** [comment]
@brbowers I am having the same issue. Have tried everything minus moving to gtm.

**Comment by macbookandrew** [comment]
@brbowers @jsadd19 Please upgrade to v1.8.1, released today. That should fix the issue.

**Comment by brbowers** [comment]
The upgrade did produce the "mail sent" and "sent" logging in GA real time events (when using GA gtag code) but not registering conversions based on Goals I've established. I did get Conversions working in 1.8.0 plugin which tells me my goals were set up correctly by

using old analytics.js along with:



<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXXXXX-X', 'auto');
ga('send', 'pageview');
</script>

AND

<script>
document.addEventListener( 'wpcf7mailsent', function( event ) {
    ga('send', 'event', 'Contact Form', 'submit', 'Contact Form');
}, false );
</script>


is the wpcf7 EventListener above needed?


I appreciate your assistance.

Thanks!

Bryan

________________________________

**Comment by macbookandrew** [comment]
@brbowers Sounds like your goals are using “Contact Form” instead of “Contact Form 7” for the category? Please double-check your goals against this list: https://wordpress.org/plugins/cf7-google-analytics/#how%20do%20i%20set%20a%20goal%20in%20google%20analytics%3F

I intentionally used “Contact Form 7” instead of “Contact Form” in my plugin to make it clear exactly where the events originated.

Thanks
