### ISSUE TITLE
PHP Warning in Playground

### ISSUE THREAD

**Issue by Zodiac1978** [macbookandrew/cf7-google-analytics#9]
I've tested this plugin in playground, but got a warning:

> Warning: Trying to access array offset on value of type bool in /wordpress/wp-content/plugins/cf7-google-analytics/inc/class-cf7-google-analytics.php on line 110

See: https://playground.wordpress.net/?login=1&url=%2Fwp-admin%2Fplugins.php&plugin=cf7-google-analytics

**Comment by macbookandrew** [comment]
@Zodiac1978 thanks; v1.8.9 should resolve this

**Comment by Zodiac1978** [comment]
Wow! Thanks for the fast fix :)
